### ISSUE TITLE
Resolve error in MetaDB app during request handling (neo4j "saveRequest()" method)

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#260]
An exception is being thrown during the `saveRequest(....)` call

```
Error during request handling: Incorrect result size: expected at most 1
org.springframework.dao.IncorrectResultSizeDataAccessException: Incorrect result size: expected at most 1
	at org.springframework.data.neo4j.repository.query.GraphQueryExecution$SingleEntityExecution.execute(GraphQueryExecution.java:73)
	at org.springframework.data.neo4j.repository.query.GraphRepositoryQuery.doExecute(GraphRepositoryQuery.java:76)
	at org.springframework.data.neo4j.repository.query.AbstractGraphRepositoryQuery.execute(AbstractGraphRepositoryQuery.java:57)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy82.findPatientByPatientAlias(Unknown Source)
	at org.mskcc.cmo.metadb.service.impl.SampleServiceImpl.saveSampleMetadata(SampleServiceImpl.java:32)
	at org.mskcc.cmo.metadb.service.impl.MetaDbRequestServiceImpl.saveRequest(MetaDbRequestServiceImpl.java:60)
	at org.mskcc.cmo.metadb.service.impl.MetaDbRequestServiceImpl$$FastClassBySpringCGLIB$$a62051ef.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at org.mskcc.cmo.metadb.service.impl.MetaDbRequestServiceImpl$$EnhancerBySpringCGLIB$$78e8a3f3.saveRequest(<generated>)
	at org.mskcc.cmo.metadb.service.impl.MessageHandlingServiceImpl$NewIgoRequestHandler.run(MessageHandlingServiceImpl.java:69)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ao508** [comment]
After some investigation we found that the error was getting thrown due to multiple patient nodes being returned when only one was expected, which was due to missing cmo patient labels in the request json response.

This is the case for LIMS requests which are not from the CMO. The `cmoRequest` field isn't reliable (see #metadb-pm discussion on May 19)

Some of the logic involved in setting `cmoRequest` status: 
https://github.com/mskcc/LimsRest/wiki/IGO-LIMS-REST-API#is-a-request-a-cmo-request

https://github.com/mskcc/LimsRest/blob/31f56b1665639d6456d01be8ea7893af09eb5c1a/src/main/java/org/mskcc/limsrest/service/cmorequests/CheckOrMarkCmoRequestsTask.java#L24

**Comment by ao508** [comment]
Linked issue https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/cmo-metadb/269
