### ISSUE TITLE
DEV BUG FIX: Unknown property in SampleMetadata [label-generator and/or cmo-metadb]

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#406]
I suspect that this field is being introduced when the `label-generator` app is fetching existing patient-samples from MetaDB through the request-reply service since I saw the same error referring to fields: `projectManagerName` and `metaDbRequestId`.

Double check what the request-reply response body looks like when getting patient samples from MetaDB and make note of what fields are not modeled in `SampleMetadata`.

- Related question: Why are request fields being added to `SampleMetadata`?

Related stack trace

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "projectManagerName" (class org.mskcc.cmo.metadb.model.SampleMetadata), not marked as ignorable (36 known properties: "sampleType", "tumorType", "requestId", "igoId", "qcReports", "recipe", "sampleName", "oncoTreeCode", "baitSet", "libraries", "fastqPath", "preservation", "metaDbPatientId", "tissueSource", "specimenType", "cmoSampleIdFields", "sex", "metaDbSampleId", "cmoSampleClass", "investigatorSampleId", "sampleOrigin", "importDate", "principalInvestigator", "cmoInfoIgoId", "cmoSampleName", "collectionYear", "species", "tubeId", "ancestorSample", "mrn", "tumorOrNormal", "cfDNA2dBarcode", "sampleStatus", "parentTumorType", "cmoPatientId", "tissueLocation"])
 at [Source: (StringReader); line: 1, column: 67] (through reference chain: org.mskcc.cmo.metadb.model.SampleMetadata["projectManagerName"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434) ~[jackson-databind-2.11.2.jar!/:2.11.2]
	at org.mskcc.cmo.metadb.service.impl.MessageHandlingServiceImpl$3.onMessage(MessageHandlingServiceImpl.java:406) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.cmo.messaging.impl.JSGatewayImpl.onMessage(JSGatewayImpl.java:202) [cmo-messaging-java-c12bb160613ecf7bab6b3af8ee05044b17b69e3d.jar!/:0.0.1-SNAPSHOT]
	at org.mskcc.cmo.messaging.impl.JSGatewayImpl.lambda$subscribe$0(JSGatewayImpl.java:165) [cmo-messaging-java-c12bb160613ecf7bab6b3af8ee05044b17b69e3d.jar!/:0.0.1-SNAPSHOT]
	at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:98) ~[jnats-2.10.0.jar!/:2.10.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_302]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_302]
```

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/cmo-metadb/406?planning-poker) with ZenHub @divyamadala30

**Comment by ao508** [comment]
Resolved by a bug fix in the messaging library that wasn't filtering messages by subject properly
