### ISSUE TITLE
DEV BUG FIX: Cannot cast Boolean to string error (MetadbRequest java model) [cmo-metadb]

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#407]
- error with casting boolean to string because wrong method was used to parse string value [fix applied here](https://github.com/mskcc/cmo-metadb/pull/369/files#diff-6d242e3550b424b106c01d9c3a879d84abed63f541775102899ec33085b76580R401)

Stacktrace
```
2021-09-29 21:45:50.868 ERROR 1 --- [pool-2-thread-2] o.m.c.m.s.i.MessageHandlingServiceImpl   : Error during handling of request metadata update

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at org.mskcc.cmo.metadb.model.MetadbRequest.updateRequestMetadata(MetadbRequest.java:401) ~[model-0.1.0.jar!/:0.1.0]
	at org.mskcc.cmo.metadb.service.impl.MessageHandlingServiceImpl$RequestMetadataUpdateHandler.run(MessageHandlingServiceImpl.java:160) ~[service-0.1.0.jar!/:0.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]
```

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/cmo-metadb/407?planning-poker) with ZenHub @divyamadala30
