### ISSUE TITLE
DEV BUG FIX: Error during handling of request metadata update [cmo-metadb-common]

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#408]
This affects the MetadbJsonComparator so the fix will need to be applied to the `cmo-metadb-common` repo

This might be related to the NPE/LinkedBlockingQueue error (card #410). If it is NOT related then this is a separate effort. If it IS then we can consolidate this card with #410 

Stack trace:

```
2021-09-30 16:45:15.562 ERROR 1 --- [pool-2-thread-2] o.m.c.m.s.i.MessageHandlingServiceImpl   : Error during handling of request metadata update

java.lang.ClassCastException: com.fasterxml.jackson.databind.node.NullNode cannot be cast to com.fasterxml.jackson.databind.node.ObjectNode
	at org.mskcc.cmo.common.impl.MetadbJsonComparatorImpl.getFilteredJsonString(MetadbJsonComparatorImpl.java:70) ~[cmo-metadb-common-7a2991cd9ecdb52400c2350286dbf9b2d360c3b1.jar!/:1.0.0-SNAPSHOT]
	at org.mskcc.cmo.common.impl.MetadbJsonComparatorImpl.isConsistent(MetadbJsonComparatorImpl.java:49) ~[cmo-metadb-common-7a2991cd9ecdb52400c2350286dbf9b2d360c3b1.jar!/:1.0.0-SNAPSHOT]
	at org.mskcc.cmo.common.impl.MetadbJsonComparatorImpl.isConsistent(MetadbJsonComparatorImpl.java:39) ~[cmo-metadb-common-7a2991cd9ecdb52400c2350286dbf9b2d360c3b1.jar!/:1.0.0-SNAPSHOT]
	at org.mskcc.cmo.metadb.service.impl.RequestServiceImpl.requestHasMetadataUpdates(RequestServiceImpl.java:210) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.cmo.metadb.service.impl.RequestServiceImpl$$FastClassBySpringCGLIB$$13b363ac.invoke(<generated>) ~[service-0.1.0.jar!/:0.1.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.mskcc.cmo.metadb.service.impl.RequestServiceImpl$$EnhancerBySpringCGLIB$$f5647904.requestHasMetadataUpdates(<generated>) ~[service-0.1.0.jar!/:0.1.0]
	at org.mskcc.cmo.metadb.service.impl.MessageHandlingServiceImpl$RequestMetadataUpdateHandler.run(MessageHandlingServiceImpl.java:168) ~[service-0.1.0.jar!/:0.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]
```

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/cmo-metadb/408?planning-poker) with ZenHub @divyamadala30

**Comment by ao508** [comment]
Resolved by a bug fix in the messaging library that wasn't filtering messages by subject properly
