### ISSUE TITLE
DEV BUG FIX: NPE during request handling

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#410]
Error seems to point to the LinkedBlockingQueue.. might just be a simple fix that checks if the response from `queue.poll(....)` is null or not

Related stack trace:

```
2021-09-30 16:46:40.240 ERROR 1 --- [pool-2-thread-1] o.m.c.m.s.i.MessageHandlingServiceImpl   : Error during request handling

java.lang.NullPointerException: null
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:411) ~[na:1.8.0_302]
	at java.util.AbstractQueue.add(AbstractQueue.java:95) ~[na:1.8.0_302]
	at org.mskcc.cmo.metadb.service.impl.MessageHandlingServiceImpl$NewIgoRequestHandler.run(MessageHandlingServiceImpl.java:118) ~[service-0.1.0.jar!/:0.1.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]
```

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/cmo-metadb/410?planning-poker) with ZenHub @divyamadala30

**Comment by ao508** [comment]
For some reason the `.saveRequest()` is being called on a request where the request JSON string is null? But not sure why it's being set up this way.. unless it's some other error that is actually happening and it's just being masked as this instead?

Running on dev server:

cmo-metadb docker image: `ochoaa/cmo-metadb:1.1.7-RC`
